language: java
sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq tightvncserver
- mkdir -p ~/.vnc
- cp kigyojatek/src/test/resources/scripts/passwd ~/.vnc/
jdk:
  - oraclejdk8
script: mvn test install -Dmaven.javadoc.skip=true -B -V ; 
# safelist
branches:
  only:
  - master