language: java
sudo: required
before_install:
- sudo apt-get update -qq
jdk:
  - oraclejdk8
script: mvn test install -Dmaven.javadoc.skip=true -B -V ; 
# safelist
branches:
  only:
  - master